app: rpa-x
service: demo-01

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: handler.handler
    #  events:
    #    - httpApi:
    #        path: /
    #        method: get
      #  - schedule:
      #      rate: cron(38 12 * * ? *)
      #      timezone: 'America/lima'
      #      input:.
      #        provider: ejemplo-aws
      #        is_delta: true

plugins:
  - serverless-python-requirements
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    usePipenv: false
